// Mapeamento expandido de títulos de exames para nomes de templates
// Baseado em compêndios médicos brasileiros (CFM, ANVISA, SBPC/ML, SBC, SBD, SBN, SBEM, SBH, CBR)
// Resoluções CFM: 2299/2021, 2381/2024

export const EXAME_TEMPLATE_MAP: Record<string, string> = {
  // ========== HEMATOLOGIA (SBHH - Sociedade Brasileira de Hematologia) ==========
  'hemograma completo': 'hemograma_completo',
  'hemograma': 'hemograma_completo',
  'hemograma com plaquetas': 'hemograma_completo',
  'hemograma cbc': 'hemograma_completo',
  'hemograma completo cbc': 'hemograma_completo',
  'cbc': 'hemograma_completo',
  'coagulograma': 'hemograma_completo',
  'plaquetas': 'hemograma_completo',
  'reticulócitos': 'hemograma_completo',
  'reticulocitos': 'hemograma_completo',
  'velocidade de hemossedimentação': 'hemograma_completo',
  'vhs': 'hemograma_completo',
  'proteína c reativa': 'hemograma_completo',
  'proteina c reativa': 'hemograma_completo',
  'pcr': 'hemograma_completo',
  'ferritina': 'ferritina',
  'ferritina sérica': 'ferritina',
  'ferritina serica': 'ferritina',
  'ferro sérico': 'ferritina',
  'ferro serico': 'ferritina',
  'transferrina': 'ferritina',
  'vitamina b12': 'hemograma_completo',
  'vitamina b 12': 'hemograma_completo',
  'cobalamina': 'hemograma_completo',
  'ácido fólico': 'hemograma_completo',
  'acido folico': 'hemograma_completo',
  'vitamina b9': 'hemograma_completo',
  'folato': 'hemograma_completo',
  
  // ========== GLICEMIA E METABOLISMO (SBD - Sociedade Brasileira de Diabetes) ==========
  'glicemia': 'glicemia',
  'glicemia em jejum': 'glicemia_jejum',
  'glicemia de jejum': 'glicemia_jejum',
  'glicemia pós-prandial': 'glicemia',
  'glicemia pos prandial': 'glicemia',
  'glicemia pós prandial': 'glicemia',
  'hemoglobina glicada': 'glicemia',
  'hemoglobina glicosilada': 'glicemia',
  'hba1c': 'glicemia',
  'hb a1c': 'glicemia',
  'curva glicêmica': 'glicemia',
  'curva glicemica': 'glicemia',
  'teste de tolerância a glicose': 'glicemia',
  'teste de tolerancia a glicose': 'glicemia',
  'ttg': 'glicemia',
  'insulina': 'glicemia',
  'peptídeo c': 'glicemia',
  'peptideo c': 'glicemia',
  
  // ========== LIPÍDIOS (SBC - Sociedade Brasileira de Cardiologia) ==========
  'colesterol': 'colesterol_total',
  'colesterol total': 'colesterol_total',
  'colesterol hdl': 'colesterol_total',
  'colesterol ldl': 'colesterol_total',
  'colesterol vldl': 'colesterol_total',
  'perfil lipídico': 'colesterol_total',
  'perfil lipidico': 'colesterol_total',
  'lipidograma': 'colesterol_total',
  'triglicerídeos': 'triglicerideos',
  'triglicerides': 'triglicerideos',
  'triglicérides': 'triglicerideos',
  'trigliceridos': 'triglicerideos',
  
  // ========== FUNÇÃO HEPÁTICA (SBH - Sociedade Brasileira de Hepatologia) ==========
  'tgo': 'tgo_tgp',
  'ast': 'tgo_tgp',
  'transaminase glutâmico oxalacética': 'tgo_tgp',
  'tgp': 'tgo_tgp',
  'alt': 'tgo_tgp',
  'transaminase glutâmico pirúvica': 'tgo_tgp',
  'tgo e tgp': 'tgo_tgp',
  'transaminases': 'tgo_tgp',
  'enzimas hepáticas': 'tgo_tgp',
  'enzimas hepaticas': 'tgo_tgp',
  'gama gt': 'tgo_tgp',
  'ggt': 'tgo_tgp',
  'gama glutamil transferase': 'tgo_tgp',
  'fosfatase alcalina': 'tgo_tgp',
  'bilirrubina total': 'tgo_tgp',
  'bilirrubina direta': 'tgo_tgp',
  'bilirrubina indireta': 'tgo_tgp',
  'albumina': 'tgo_tgp',
  'proteínas totais': 'tgo_tgp',
  'proteinas totais': 'tgo_tgp',
  'tempo de protrombina': 'tgo_tgp',
  'tp': 'tgo_tgp',
  'inr': 'tgo_tgp',
  
  // ========== FUNÇÃO RENAL (SBN - Sociedade Brasileira de Nefrologia) ==========
  'creatinina': 'funcao_renal',
  'ureia': 'funcao_renal',
  'uréia': 'funcao_renal',
  'bun': 'funcao_renal',
  'função renal': 'funcao_renal',
  'funcao renal': 'funcao_renal',
  'depuração de creatinina': 'funcao_renal',
  'depuracao de creatinina': 'funcao_renal',
  'clearance de creatinina': 'funcao_renal',
  'ácido úrico': 'acido_urico',
  'acido urico': 'acido_urico',
  'microalbuminúria': 'funcao_renal',
  'microalbuminuria': 'funcao_renal',
  'proteinúria': 'funcao_renal',
  'proteinuria': 'funcao_renal',
  'eletrólitos': 'eletrolitos',
  'eletrólitos séricos': 'eletrolitos',
  'eletrolitos sericos': 'eletrolitos',
  'sódio': 'eletrolitos',
  'sodio': 'eletrolitos',
  'na': 'eletrolitos',
  'potássio': 'eletrolitos',
  'potassio': 'eletrolitos',
  'k': 'eletrolitos',
  'cloro': 'eletrolitos',
  'cl': 'eletrolitos',
  'magnésio': 'eletrolitos',
  'magnesio': 'eletrolitos',
  'mg': 'eletrolitos',
  'fósforo': 'eletrolitos',
  'fosforo': 'eletrolitos',
  'p': 'eletrolitos',
  'cálcio': 'eletrolitos',
  'calcio': 'eletrolitos',
  'ca': 'eletrolitos',
  
  // ========== FUNÇÃO TIROIDEANA (SBEM - Sociedade Brasileira de Endocrinologia) ==========
  'tsh': 'tsh_t4',
  't4 livre': 'tsh_t4',
  't4l': 'tsh_t4',
  'free t4': 'tsh_t4',
  't3 livre': 'tsh_t4',
  't3l': 'tsh_t4',
  'free t3': 'tsh_t4',
  't4 total': 'tsh_t4',
  't3 total': 'tsh_t4',
  'hormônios tireoidianos': 'tsh_t4',
  'hormonios tireoidianos': 'tsh_t4',
  'perfil tireoidiano': 'tsh_t4',
  'anti tpo': 'tsh_t4',
  'anti-tpo': 'tsh_t4',
  'antitpo': 'tsh_t4',
  'anti tg': 'tsh_t4',
  'anti-tg': 'tsh_t4',
  'antitg': 'tsh_t4',
  
  // ========== VITAMINAS E MINERAIS ==========
  'vitamina d': 'vitamina_d',
  'vitamina d3': 'vitamina_d',
  '25 oh vitamina d': 'vitamina_d',
  '25-oh vitamina d': 'vitamina_d',
  'calcidiol': 'vitamina_d',
  'zinco': 'eletrolitos',
  'selênio': 'eletrolitos',
  'selenio': 'eletrolitos',
  
  // ========== MARCADORES TUMORAIS (SBCO - Sociedade Brasileira de Cancerologia) ==========
  'psa': 'psa',
  'antígeno prostático específico': 'psa',
  'antigeno prostatico especifico': 'psa',
  'psa total': 'psa',
  'psa livre': 'psa',
  'cea': 'psa',
  'antígeno carcinoembrionário': 'psa',
  'antigeno carcinoembrionario': 'psa',
  'ca 125': 'psa',
  'ca 19-9': 'psa',
  'ca 15-3': 'psa',
  'afp': 'psa',
  'alfafetoproteína': 'psa',
  'alfafetoproteina': 'psa',
  'b2 microglobulina': 'psa',
  
  // ========== PÂNCREAS E FUNÇÃO DIGESTIVA ==========
  'amilase': 'amilase_lipase',
  'lipase': 'amilase_lipase',
  'amilase e lipase': 'amilase_lipase',
  'amilase sérica': 'amilase_lipase',
  'amilase serica': 'amilase_lipase',
  'lipase sérica': 'amilase_lipase',
  'lipase serica': 'amilase_lipase',
  'elastase fecal': 'amilase_lipase',
  'elastase pancreática': 'amilase_lipase',
  'elastase pancreatica': 'amilase_lipase',
  
  // ========== CORAÇÃO E MARCADORES CARDÍACOS (SBC - Sociedade Brasileira de Cardiologia) ==========
  'bnp': 'bnp',
  'nt-probnp': 'bnp',
  'peptídeo natriurético': 'bnp',
  'peptideo natriuretico': 'bnp',
  'troponina': 'bnp',
  'troponina i': 'bnp',
  'troponina t': 'bnp',
  'ck-mb': 'bnp',
  'ckmb': 'bnp',
  'creatinoquinase': 'bnp',
  'ck': 'bnp',
  'cpk': 'bnp',
  'lactato desidrogenase': 'bnp',
  'ldh': 'bnp',
  
  // ========== HORMÔNIOS E FERTILIDADE (SBEM - Sociedade Brasileira de Endocrinologia) ==========
  'testosterona': 'tsh_t4',
  'testosterona total': 'tsh_t4',
  'testosterona livre': 'tsh_t4',
  'lh': 'tsh_t4',
  'hormônio luteinizante': 'tsh_t4',
  'hormonio luteinizante': 'tsh_t4',
  'fsh': 'tsh_t4',
  'hormônio folículo estimulante': 'tsh_t4',
  'hormonio folículo estimulante': 'tsh_t4',
  'prolactina': 'tsh_t4',
  'estradiol': 'tsh_t4',
  'estrógeno': 'tsh_t4',
  'estrogeno': 'tsh_t4',
  'progesterona': 'tsh_t4',
  'cortisol': 'tsh_t4',
  'cortisol sérico': 'tsh_t4',
  'cortisol serico': 'tsh_t4',
  'acth': 'tsh_t4',
  'hormônio adrenocorticotrófico': 'tsh_t4',
  'aldosterona': 'eletrolitos',
  'renina': 'eletrolitos',
  
  // ========== IMAGEM - ULTRASSONOGRAFIA (CBR - Colégio Brasileiro de Radiologia) ==========
  'ultrassonografia': 'ultrassonografia',
  'ultrassom': 'ultrassonografia',
  'ecografia': 'ultrassonografia',
  'ultrassonografia abdominal': 'ultrassonografia_abdomen',
  'ultrassonografia de abdômen': 'ultrassonografia_abdomen',
  'ultrassonografia de abdomen': 'ultrassonografia_abdomen',
  'ultrassom abdominal': 'ultrassonografia_abdomen',
  'ultrassom de abdômen': 'ultrassonografia_abdomen',
  'usg abdominal': 'ultrassonografia_abdomen',
  'ultrassonografia pélvica': 'ultrassonografia',
  'ultrassonografia pelvica': 'ultrassonografia',
  'ultrassom pélvico': 'ultrassonografia',
  'ultrassom pelvico': 'ultrassonografia',
  'ultrassonografia transvaginal': 'ultrassonografia',
  'ultrassom transvaginal': 'ultrassonografia',
  'ultrassonografia de próstata': 'ultrassonografia',
  'ultrassonografia de prostata': 'ultrassonografia',
  'ultrassom de próstata': 'ultrassonografia',
  'ultrassom de prostata': 'ultrassonografia',
  'ultrassonografia obstétrica': 'ultrassonografia',
  'ultrassonografia obstetrica': 'ultrassonografia',
  'ultrassom obstétrico': 'ultrassonografia',
  'ultrassom obstetrico': 'ultrassonografia',
  'ultrassonografia doppler': 'ultrassonografia',
  'doppler': 'ultrassonografia',
  'doppler vascular': 'ultrassonografia',
  'doppler carotídeo': 'ultrassonografia',
  'doppler carotideo': 'ultrassonografia',
  'ultrassonografia renal': 'ultrassonografia',
  'ultrassom renal': 'ultrassonografia',
  'ultrassonografia vesical': 'ultrassonografia',
  'ultrassom vesical': 'ultrassonografia',
  
  // ========== IMAGEM - RADIOLOGIA (CBR - Colégio Brasileiro de Radiologia) ==========
  'raio-x': 'raio_x',
  'raio x': 'raio_x',
  'radiografia': 'raio_x',
  'radiografia de tórax': 'raio_x',
  'radiografia de torax': 'raio_x',
  'radiografia de tórax pa': 'raio_x',
  'radiografia simples': 'raio_x',
  'rx': 'raio_x',
  'rx tórax': 'raio_x',
  'rx torax': 'raio_x',
  
  // ========== IMAGEM - TOMOGRAFIA (CBR - Colégio Brasileiro de Radiologia) ==========
  'tomografia': 'tomografia',
  'tomografia computadorizada': 'tomografia',
  'tc': 'tomografia',
  'ct scan': 'tomografia',
  'tomografia de crânio': 'tomografia',
  'tomografia de cranio': 'tomografia',
  'tc crânio': 'tomografia',
  'tc cranio': 'tomografia',
  'tomografia de tórax': 'tomografia',
  'tomografia de torax': 'tomografia',
  'tc tórax': 'tomografia',
  'tc torax': 'tomografia',
  'tomografia de abdômen': 'tomografia_abdomen',
  'tomografia de abdomen': 'tomografia_abdomen',
  'tomografia abdominal': 'tomografia_abdomen',
  'tc abdômen': 'tomografia_abdomen',
  'tc abdomen': 'tomografia_abdomen',
  'tomografia de pelve': 'tomografia',
  'tc pelve': 'tomografia',
  
  // ========== IMAGEM - RESSONÂNCIA (CBR - Colégio Brasileiro de Radiologia) ==========
  'ressonância magnética': 'ressonancia_magnetica',
  'ressonancia magnetica': 'ressonancia_magnetica',
  'ressonância': 'ressonancia_magnetica',
  'ressonancia': 'ressonancia_magnetica',
  'rm': 'ressonancia_magnetica',
  'mri': 'ressonancia_magnetica',
  'ressonância de crânio': 'ressonancia_magnetica',
  'ressonancia de cranio': 'ressonancia_magnetica',
  'rm crânio': 'ressonancia_magnetica',
  'rm cranio': 'ressonancia_magnetica',
  'ressonância de coluna': 'ressonancia_magnetica',
  'ressonancia de coluna': 'ressonancia_magnetica',
  'rm coluna': 'ressonancia_magnetica',
  'ressonância de joelho': 'ressonancia_magnetica',
  'ressonancia de joelho': 'ressonancia_magnetica',
  'rm joelho': 'ressonancia_magnetica',
  
  // ========== IMAGEM - MAMOGRAFIA (CBR - Colégio Brasileiro de Radiologia) ==========
  'mamografia': 'mamografia',
  'mamografia bilateral': 'mamografia',
  'mamografia de rastreamento': 'mamografia',
  'mamografia diagnóstica': 'mamografia',
  'mamografia diagnostica': 'mamografia',
  
  // ========== CARDIOLOGIA (SBC - Sociedade Brasileira de Cardiologia) ==========
  'eletrocardiograma': 'eletrocardiograma',
  'ecg': 'eletrocardiograma',
  'eletro': 'eletrocardiograma',
  'teste ergométrico': 'teste_ergometrico',
  'teste de esforço': 'teste_ergometrico',
  'teste de esforco': 'teste_ergometrico',
  'ergometria': 'teste_ergometrico',
  'holter': 'holter',
  'holter 24h': 'holter',
  'holter de 24 horas': 'holter',
  'monitoramento ambulatorial da pressão arterial': 'mapa',
  'monitoramento ambulatorial da pressao arterial': 'mapa',
  'mapa': 'mapa',
  'mapa 24h': 'mapa',
  'ecocardiograma': 'ecocardiograma',
  'ecocardiograma transtorácico': 'ecocardiograma',
  'ecocardiograma transtoracico': 'ecocardiograma',
  'eco': 'ecocardiograma',
  'ecocardiograma transesofágico': 'ecocardiograma',
  'ecocardiograma transesofagico': 'ecocardiograma',
  'ete': 'ecocardiograma',
  
  // ========== ENDOSCOPIA (SOBED - Sociedade Brasileira de Endoscopia Digestiva) ==========
  'endoscopia': 'endoscopia',
  'endoscopia digestiva alta': 'endoscopia',
  'endoscopia digestiva': 'endoscopia',
  'eda': 'endoscopia',
  'endoscopia digestiva alta com biópsia': 'endoscopia',
  'endoscopia digestiva alta com biopsia': 'endoscopia',
  'endoscopia com biópsia': 'endoscopia',
  'endoscopia com biopsia': 'endoscopia',
  'colonoscopia': 'colonoscopia',
  'colonoscopia total': 'colonoscopia',
  'colonoscopia com biópsia': 'colonoscopia',
  'colonoscopia com biopsia': 'colonoscopia',
  'retossigmoidoscopia': 'colonoscopia',
  'retossigmoidoscopia': 'colonoscopia',
  
  // ========== GINECOLOGIA (FEBRASGO - Federação Brasileira das Associações de Ginecologia) ==========
  'papanicolau': 'papanicolau',
  'preventivo': 'papanicolau',
  'citologia oncótica': 'papanicolau',
  'citologia oncotica': 'papanicolau',
  'colpocitologia oncótica': 'papanicolau',
  'colpocitologia oncotica': 'papanicolau',
  'exame citopatológico': 'papanicolau',
  'exame citopatologico': 'papanicolau',
  'coleta de material para citologia': 'papanicolau',
  'colposcopia': 'papanicolau',
  'histeroscopia': 'papanicolau',
  'vulvoscopia': 'papanicolau',
  
  // ========== UROLOGIA (SBU - Sociedade Brasileira de Urologia) ==========
  'urocult': 'papanicolau',
  'urocultura': 'papanicolau',
  'exame de urina': 'papanicolau',
  'eas': 'papanicolau',
  'elementos anormais e sedimentos': 'papanicolau',
  'uroanálise': 'papanicolau',
  'uroanalise': 'papanicolau',
  'urinálise': 'papanicolau',
  'urinalise': 'papanicolau',
  
  // ========== INFECTOLOGIA E SOROLOGIA (SBI - Sociedade Brasileira de Infectologia) ==========
  'sorologia': 'papanicolau',
  'hiv': 'papanicolau',
  'anti hiv': 'papanicolau',
  'vírus da imunodeficiência humana': 'papanicolau',
  'virus da imunodificiencia humana': 'papanicolau',
  'hepatite a': 'tgo_tgp',
  'anti hav': 'tgo_tgp',
  'hepatite b': 'tgo_tgp',
  'hbsag': 'tgo_tgp',
  'anti hbc': 'tgo_tgp',
  'anti hbs': 'tgo_tgp',
  'hepatite c': 'tgo_tgp',
  'anti hcv': 'tgo_tgp',
  'vdrl': 'papanicolau',
  'rpr': 'papanicolau',
  'treponema pallidum': 'papanicolau',
  'sífilis': 'papanicolau',
  'sifilis': 'papanicolau',
  'toxoplasmose': 'papanicolau',
  'anti toxoplasma': 'papanicolau',
  'rubéola': 'papanicolau',
  'rubeola': 'papanicolau',
  'anti rubéola': 'papanicolau',
  'anti rubeola': 'papanicolau',
  'citomegalovírus': 'papanicolau',
  'citomegalovirus': 'papanicolau',
  'cmv': 'papanicolau',
  'anti cmv': 'papanicolau',
  'mononucleose': 'papanicolau',
  'ebv': 'papanicolau',
  'anti ebv': 'papanicolau',
  
  // ========== ALERGIA E IMUNOLOGIA (ASBAI - Associação Brasileira de Alergia e Imunologia) ==========
  'ige total': 'papanicolau',
  'imunoglobulina e': 'papanicolau',
  'ige específica': 'papanicolau',
  'ige especifica': 'papanicolau',
  'painel de alérgenos': 'papanicolau',
  'painel de alergenos': 'papanicolau',
  'teste de alergia': 'papanicolau',
  
  // ========== OUTROS EXAMES COMUNS ==========
  'parasitológico de fezes': 'papanicolau',
  'parasitologico de fezes': 'papanicolau',
  'coprocultura': 'papanicolau',
  'exame parasitológico': 'papanicolau',
  'exame parasitologico': 'papanicolau',
  'parasita': 'papanicolau',
  'cultura de fezes': 'papanicolau',
  'densitometria óssea': 'ultrassonografia',
  'densitometria ossea': 'ultrassonografia',
  'dxa': 'ultrassonografia',
};

/**
 * Normaliza o título do exame para encontrar o template correspondente
 */
export function normalizeExameTitle(titulo: string): string {
  if (!titulo) return 'exame_generico';
  
  const normalized = titulo.toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // Remove acentos
    .trim();
  
  // Buscar correspondência exata ou parcial
  for (const [key, template] of Object.entries(EXAME_TEMPLATE_MAP)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return template;
    }
  }
  
  // Se não encontrar, criar nome baseado no título
  return normalized
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 50) || 'exame_generico';
}
