create table if not exists password_recovery_tokens (
  id bigint generated by default as identity primary key,
  email text not null,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz,
  request_ip text,
  request_user_agent text,
  used_ip text,
  used_user_agent text
);

create index if not exists password_recovery_tokens_email_idx
  on password_recovery_tokens (email);

create index if not exists password_recovery_tokens_expires_idx
  on password_recovery_tokens (expires_at);

create index if not exists password_recovery_tokens_used_idx
  on password_recovery_tokens (used_at);

alter table password_recovery_tokens enable row level security;
